# README
# use this file to store different setup for retrieval spectral windows
# use the "windows" key in the --toml-file you want to use (e.g. see o2_test_setup.toml) to complement the control_setup.toml information
# special syntax: use "=key" as a value so that control_setup.py will replace it with the value of the given key (only works when referring to first level keys, ignoring "FILES", "RETRIEVAL" etc)

[co2_window.fwd_inv_mode_options.co2_window]
index = 1
start_nm = 1595.0
end_nm = 1618.0
buffer_nm = 2.0
convolution_grid_sampling = 0.01
radiative_transfer_model = "TRNMSN"
isrf = "MAirCal"
convolution_width_hw1e = 10.0
use_fft_for_convolution = "F"

[co2_window.l2_surface_reflectance.band_inputs.weakch4]
name = "WeakCH4"
file_type = "SPLAT"
index = 1

[co2_window.l1_radiance.band_inputs.weakch4]
name = "WeakCH4"
file_type = "SPLAT"
index = 1
file = "=l1_file"

[ch4_window.fwd_inv_mode_options.ch4_window]
index = 1
start_nm = 1629.0
end_nm = 1654.0
buffer_nm = 2.0
convolution_grid_sampling = 0.01
radiative_transfer_model = "TRNMSN"
isrf = "MAirCal"
convolution_width_hw1e = 10.0
use_fft_for_convolution = "F"

[ch4_window.l2_surface_reflectance.band_inputs.weakch4]
name = "WeakCH4"
file_type = "SPLAT"
index = 1
file = "=l2_met_file"

[ch4_window.l1_radiance.band_inputs.weakch4]
name = "WeakCH4"
file_type = "SPLAT"
index = 1
file = "=l1_file"

[o2_window.fwd_inv_mode_options.o2_window]
index = 1
start_nm = 1249.2
end_nm = 1287.8
buffer_nm = 2.0
convolution_grid_sampling = 0.004
radiative_transfer_model = "TRNMSN"
isrf = "MAirCal"
convolution_width_hw1e = 10.0
use_fft_for_convolution = "F"

[o2_window.l2_surface_reflectance.band_inputs.o2delta]
name = "O2Delta"
file_type = "SPLAT"
index = 1
file = "=l2_met_file"

[o2_window.l1_radiance.band_inputs.o2delta]
name = "O2Delta"
file_type = "SPLAT"
index = 1
file = "=l1_file"
