# README
# control_setup.py reads inputs from control_setup.toml
# It then reads this file (ch4_test_setup.toml) as well as xsec.toml and window.toml to overwrite the fields from control_setup.toml
# finally it fills the template.control with this information

##################################
#### START OF REQUIRED fields ####
##################################
root_data_directory = "/n/holylfs04/LABS/wofsy_lab/Lab/sroche/splat_static/SPLAT/data"
l1_file = "/n/holylfs04/LABS/wofsy_lab/Lab/MethaneAIR/level1/RF06_V3/CH4_NATIVE/MethaneAIR_L1B_CH4_20210806T173908_20210806T173918_20210930T114856.nc"
l2_met_file = "/n/holylfs04/LABS/wofsy_lab/Lab/MethaneAIR/level2/2022_Reprocess/RF06/L2Met_CH4_NATIVE/MethaneAIR_L1B_CH4_20210806T173908_20210806T173918_20210930T114856_prior.nc"
output_file = "/n/home11/sroche/testing/mair_json_setup_ch4_test.nc"
log_file = "/n/home11/sroche/testing/mair_json_setup_ch4_test.log"
isrf_file = "ch4_isrf_lut_20210722_xtrkflip.nc"
# specify the absorption cross section lookup table files
# Special key: xsec must specify a key defined in xsec.toml
xsec = "ggg2020_ch4"
# specify the retrieval spectral window
# Special key: windows must specify keys defined in window.toml
windows = [ "co2_window", "ch4_window",]
abs_species = [ "CH4", "H2O", "CO2",]
prf_species = [ "CH4", "CO2",]
col_species = [ "H2O",]
##################################
####  END OF REQUIRED fields  ####
##################################

isrf_agg = 1

x_start = 600
x_end = 600
y_start = 1
y_end = 1

# Surface Reflectance State Vector Options
surface_reflectance.polynomial_scaling.order = 1
surface_reflectance.polynomial_scaling.uncert_prcnt = [5, 1]
surface_reflectance.window_poly_scale.window1.order = 3
surface_reflectance.window_poly_scale.window1.uncert_prcnt = 100
surface_reflectance.window_poly_scale.window2.order = 3
surface_reflectance.window_poly_scale.window2.uncert_prcnt = 100

# Radiometric Offset State Vector Options
radiometric_offset.polynomial_scaling.order = 0
radiometric_offset.polynomial_scaling.uncert_prcnt = [5]
radiometric_offset.window_poly_scale.window1.order = 1
radiometric_offset.window_poly_scale.window1.uncert_prcnt = 5
radiometric_offset.window_poly_scale.window2.order = 1
radiometric_offset.window_poly_scale.window2.uncert_prcnt = 5

# Radiometric Scaling State Vector Options
radiometric_scaling.polynomial_scaling.order = 1
radiometric_scaling.polynomial_scaling.uncert_prcnt = [5, 5]
radiometric_scaling.window_poly_scale.window1.order = 1
radiometric_scaling.window_poly_scale.window1.uncert_prcnt = 25
radiometric_scaling.window_poly_scale.window2.order = 1
radiometric_scaling.window_poly_scale.window2.uncert_prcnt = 25

# Wavelength Grid State Vector Options
wavelength_grid.polynomial_scaling.order = 1
wavelength_grid.polynomial_scaling.uncert_prcnt = [1, 1]
wavelength_grid.window_poly_scale.window1.order = 0
wavelength_grid.window_poly_scale.window1.uncert_prcnt = 100
wavelength_grid.window_poly_scale.window2.order = 0
wavelength_grid.window_poly_scale.window2.uncert_prcnt = 100

