# README
# control_setup.py reads inputs from control_setup.toml
# It then reads this file (o2_test_setup.toml) as well as xsec.toml and window.toml to overwrite the fields from control_setup.toml
# finally it fills the template.control with this information

##################################
#### START OF REQUIRED fields ####
##################################
# the root data directory contains the static splat inputs
root_data_directory = "/n/holylfs04/LABS/wofsy_lab/Lab/sroche/splat_static/SPLAT/data"
l1_file = "/n/holyscratch01/wofsy_lab/sroche/level1/RF06_V3/O2_1x1_prio/MethaneAIR_L1B_O2_20210806T160431_20210806T160441_20210925T195340.nc"
l2_met_file = "/n/holylfs04/LABS/wofsy_lab/Lab/MethaneAIR/level2/2022_Reprocess/RF06/L2_Prior_O2_1x1/MethaneAIR_L1B_O2_20210806T160431_20210806T160441_20210925T195340_prior.nc"
output_file = "/n/home11/sroche/testing/mair_toml_setup_o2_test.nc"
log_file = "/n/home11/sroche/testing/mair_toml_setup_o2_test.log"
debug_level = "3"
isrf_file = "o2_isrf_lut_20210722_xflipped.nc"
# specify the absorption cross section lookup table files
# Special key: xsec must specify a key defined in xsec.toml
xsec = "ggg2020_o2"
# specify the retrieval spectral window
# Special key: windows must specify keys defined in window.toml
windows = [ "o2_window",]
# List of gases included in the modelled atmosphere
abs_species = [ "PACIA", "O2", "H2O", "CO2",]
# List of gases retrieved as profiles
prf_species = []
# List of gases retrieved as total columns
col_species = [ "H2O", "CO2", "PA1",]
##################################
####  END OF REQUIRED fields  ####
##################################

isrf_agg = 1

# Ranges of pixels to process, x is across-track, y is along-track
x_start = 200
x_end = 200
y_start = 1
y_end = 1

# Surface Reflectance State Vector Options
surface_reflectance.polynomial_scaling.order = 1
surface_reflectance.polynomial_scaling.uncert_prcnt = [5, 1]
surface_reflectance.window_poly_scale.window1.order = 3
surface_reflectance.window_poly_scale.window1.uncert_prcnt = 100

# Radiometric Offset State Vector Options
radiometric_offset.polynomial_scaling.order = 0
radiometric_offset.polynomial_scaling.uncert_prcnt = [5]
radiometric_offset.window_poly_scale.window1.order = 1
radiometric_offset.window_poly_scale.window1.uncert_prcnt = 5

# Radiometric Scaling State Vector Options
radiometric_scaling.polynomial_scaling.order = 1
radiometric_scaling.polynomial_scaling.uncert_prcnt = [5, 5]
radiometric_scaling.window_poly_scale.window1.order = 1
radiometric_scaling.window_poly_scale.window1.uncert_prcnt = 25

# Wavelength Grid State Vector Options
wavelength_grid.polynomial_scaling.order = 1
wavelength_grid.polynomial_scaling.uncert_prcnt = [1, 1]
wavelength_grid.window_poly_scale.window1.order = 0
wavelength_grid.window_poly_scale.window1.uncert_prcnt = 100

# The defaults for diagnostics options in control_setup.toml are set for the CH4 + CO2 windows
# Below we update fields for the O2 diagnostics

# Diagnostics options for O2
[profile_output_options.gas_partial_column]
save_prior = "T"
save_posterior = "T"
species = [ "O2", "H2O", "PA1",]
[profile_output_options.gas_column_uncertainties]
save_prior = "T"
save_posterior = "T"
species = [ "O2", "H2O", "PA1",]
[profile_output_options.gas_mixing_ratios]
save_prior = "T"
save_posterior = "T"
species = [ "O2", "H2O", "PA1",]
[profile_output_options.proxy_column_avg_mix_rat]
save_prior = "F"
save_posterior = "F"
species = [ "all",]

# Inverse diag options for O2
[sub_state_vector_diagnostics.gas_absorption_post_covar.profile_mixing_ratio]
save = "F"
species = [ "all",]

[sub_state_vector_diagnostics.gas_absorption_post_covar.column_avg_mixing_ratio]
save = "T"
species = [ "O2", "H2O", "CO2",]

[sub_state_vector_diagnostics.gas_absorption_post_covar.dry_profile_mixing_ratio]
save = "F"
species = [ "all",]

[sub_state_vector_diagnostics.gas_absorption_post_covar.dry_column_avg_mixing_ratio]
save = "T"
species = [ "O2", "H2O", "CO2",]

[sub_state_vector_diagnostics.gas_absorption_post_covar.proxy_posteriori_uncert]
save = "F"
species = [ "all",]

[sub_state_vector_diagnostics.gas_absorption_post_covar.column_averaging_kernel]
save = "T"
species = [ "CO2", "H2O",]


