# README
# use this file to store different versions or combinations of absorption cross section lookup tables
# use the "xsec" key in the --toml-file you want to use (e.g. see o2_test_setup.toml) to complement the control_setup.toml information
# only filenames should be listed here, SPLAT will look for them under {{root_data_directory}}/SAO_crosssections/splatv2_xsect
# special syntax: use "=key" as a value so that control_setup.py will replace it with the value of the given key (only works when referring to first level keys, ignoring "FILES", "RETRIEVAL" etc)

# ggg2014
[ggg2014.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_H2O_1550_1710_VP_0p01.nc"
[ggg2014.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_O2_1200_1310_VP.nc"
[ggg2014.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[ggg2014.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_CO2_1550_1710_VP_0p01.nc"
[ggg2014.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_CO_1550_1710_VP_0p01.nc"
[ggg2014.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_CH4_1600_1700_VP_0p01.nc"
[ggg2014.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2014_N2O_1550_1710_VP_0p01.nc"
[ggg2014.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# ggg2020_ch4
[ggg2020_ch4.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_H2O_1580_1670_VP_0p01.nc"
[ggg2020_o2.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_CO2_1580_1670_SDVP_LM_0p01.nc"
[ggg2020_o2.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_CH4_1580_1670_SDVP_LM_0p01.nc"

# ggg2020_o2
[ggg2020_o2.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_O2_1235_1300_SDVP_0p004.nc"
[ggg2020_o2.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_H2O_1235_1300_VP_0p004.nc"
[ggg2020_o2.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_CO2_1235_1300_VP_0p004.nc"
[ggg2020_o2.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1235_1300_PACIA_0p004_e46.nc"

# hit2016
[hitran2016.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hitran2016.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_O2_1200-1300nm_0p00.nc"
[hitran2016.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hitran2016.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_CO2_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hitran2016.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_CO_1200_1300_1550_1710_VP.nc"
[hitran2016.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_CH4_1600-1700nm_0p00_0p01dw.nc"
[hitran2016.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "GGG2020_N2O_1200_1300_1550_1710_VP.nc"
[hitran2016.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# hit2020_co2_VP
[hit2020_co2_VP.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hit2020_co2_VP.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_O2_1200_1310_VP_0p001.nc"
[hit2020_co2_VP.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hit2020_co2_VP.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO2_1550_1710_VP.nc"
[hit2020_co2_VP.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO_1550_1710_VP_0p01.nc"
[hit2020_co2_VP.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CH4_1600_1700_VP_0p01.nc"
[hit2020_co2_VP.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_N2O_1550_1710_VP_0p01.nc"
[hit2020_co2_VP.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# hit2020_co2_VP_LM
[hit2020_co2_VP_LM.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hit2020_co2_VP_LM.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_O2_1200_1310_VP_0p001.nc"
[hit2020_co2_VP_LM.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hit2020_co2_VP_LM.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO2_1550_1710_VP_LM.nc"
[hit2020_co2_VP_LM.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO_1550_1710_VP_0p01.nc"
[hit2020_co2_VP_LM.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CH4_1600_1700_VP_0p01.nc"
[hit2020_co2_VP_LM.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_N2O_1550_1710_VP_0p01.nc"
[hit2020_co2_VP_LM.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# hit2020_co2_SDVP
[hit2020_co2_SDVP.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hit2020_co2_SDVP.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_O2_1200_1310_VP_0p001.nc"
[hit2020_co2_SDVP.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hit2020_co2_SDVP.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO2_1550_1710_SDVP.nc"
[hit2020_co2_SDVP.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO_1550_1710_VP_0p01.nc"
[hit2020_co2_SDVP.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CH4_1600_1700_VP_0p01.nc"
[hit2020_co2_SDVP.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_N2O_1550_1710_VP_0p01.nc"
[hit2020_co2_SDVP.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# hit2020_co2_SDVP_LM
[hit2020_co2_SDVP_LM.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_O2_1200_1310_VP_0p001.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO2_1550_1710_SDVP_LM.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO_1550_1710_VP_0p01.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CH4_1600_1700_VP_0p01.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_N2O_1550_1710_VP_0p01.nc"
[hit2020_co2_SDVP_LM.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"

# hit2020_co2_VP_fullLM
[hit2020_co2_VP_fullLM.cross_section_entries.H2O]
name = "H2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2016_H2O_1200-1300nm_1550-1700nm_0p00_0p01dw.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.O2]
name = "O2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_O2_1200_1310_VP_0p001.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.O4]
name = "O4"
cia1 = "O2"
cia2 = "O2"
brd1 = "-"
file = "GGG2020_O2_1200_1310_ACIA_scaled.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.CO2]
name = "CO2"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO2_1550_1710_VP_fullLM.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.CO]
name = "CO"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CO_1550_1710_VP_0p01.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.CH4]
name = "CH4"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_CH4_1600_1700_VP_0p01.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.N2O]
name = "N2O"
cia1 = "-"
cia2 = "-"
brd1 = "-"
file = "HITRAN2020_N2O_1550_1710_VP_0p01.nc"
[hit2020_co2_VP_fullLM.cross_section_entries.PACIA]
name = "PACIA"
cia1 = "PA1"
cia2 = "PA1"
brd1 = "-"
file = "GGG2020_O2_1200_1310_PACIA_scaled_e46.nc"
